kind: Service
apiVersion: v1
metadata:
  name: app-service
  namespace: fuck
spec:
  type: LoadBalancer
  selector:
    app: train-app
  ports:
    - protocol: TCP
      port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: fuck
  labels:
    app: train-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train-app
      track: stable
  template:
    metadata:
      labels:
        app: train-app
        track: stable
    spec:
      containers:
        - name: train-app
          image: hitchenwenhao521/springbootapp:5.6
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
          resources:
            requests:
              cpu: 200m
